/**
 * Thresholds and defaults for analytics aggregation queries.
 */
export const analyticsConstants = {
	LAST_24H_MS: 24 * 60 * 60 * 1000,
	HTTP_STATUS_SERVER_ERROR_THRESHOLD: 500,
	HTTP_STATUS_SUCCESS_MIN: 200,
	HTTP_STATUS_SUCCESS_MAX: 300,
	DEFAULT_TIMESERIES_LIMIT: 24,
	MAX_TIMESERIES_LIMIT: 168,
	UPTIME_DIVISOR_FALLBACK: 1,
	ISO_HOUR_BUCKET_PREFIX_LENGTH: 13,
	ISO_DAY_BUCKET_PREFIX_LENGTH: 10,
} as const;
