name: Continuous Deployment
on:
  push:
    branches:
      - main

env:
  DEPLOY_PATH: /var/www/proxy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Apply migrations && Generate Prisma client
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: npm run db:migrate:deploy -w apps/backend && npm run db:generate -w apps/backend

      - name: Build backend and web application
        run: npm run build -w apps/backend && npm run build -w apps/web

      - name: Check SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}

      - name: Create target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo mkdir -p ${{ env.DEPLOY_PATH }}
            sudo chown -R ${{ secrets.AWS_EC2_USERNAME }}:${{ secrets.AWS_EC2_USERNAME }} ${{ env.DEPLOY_PATH }}
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          source: ".,!.git,!node_modules"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
          overwrite: true  

      - name: Install staging deps, Prisma client, and start backend and web applications (PM2)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            cd ${{ env.DEPLOY_PATH }}
            npm ci
            npm run db:generate -w apps/backend
            pm2 delete all 2>/dev/null || true
            pm2 start ecosystem.config.js --env staging
